### ISSUE TITLE
Göra patetsidan som en scroll i taget.

### ISSUE THREAD

**Issue by daancs** [cthit/nollk.it#1]
t.ex. att när man skrollar ner en gång så kommer man till nästa år av pateter där bakgrunden på sidan ändras till en bild på det året man är på och texten ändras också.

**Comment by ericlp** [comment]
Om du funderar på vad du ska söka på för att fixa effekten så kallas den "Parallax effect". FInns en guide här men även på många andra ställen på internet. https://www.w3schools.com/howto/howto_css_parallax.asp

**Comment by daancs** [comment]
Jag tror inte riktigt det är parallax effekt jag försöker åstadkomma. Det kanske var dåligt skrivet men menar mer att man skrollar hela sidan på en gång istället för att kunna scrolla lite i taget. Och att det med det byter bakgrund (denna behöver inte riktigt vara `background` på bodyn utan bara en bakgrund på ett stort block som finns över hela sidan)

**Comment by daancs** [comment]
Denna är nu klar, använde fullpage.js componenten för den. dock är den egentligen paid men funkar ändå
