### ISSUE TITLE
It might be cool if the Todo shows the upcoming events from the calendar?

### ISSUE THREAD

**Issue by drakejacob** [cthit/nollk.it#21]
Either way we must figure out what the todo is supposed to show during different times of the year.

Timeline:
Jan-Mar: idk fam
Mar-Maj: Phaddra
Maj-Jul: Nolldeklarera here too??
Jul-Aug: Nolldeklarera?
Aug-Sep: Arr?
Sep-Nov: Aspa
Nov-Dec: idk fam

**Comment by daancs** [comment]
jag tänker 
Jan-mar: fuck do i know lmao
typ feb/mar-maj: phaddra
~Maj-Aug: Nolldeklarera
Mottagning: Schema??
Efter mottagning: "Aspa NollKIT"
efter aspning??? (kanske grattis nollkitxx?)

**Comment by drakejacob** [comment]
If we decide to add schema-support I think it will be easier to implement once the schema is stored in a database so that it can be accessed across the pages. (Currently, the schema is hardcoded in the schema page/component)

**Comment by daancs** [comment]
I was thinking the schema would get scraped from googles calendar?

**Comment by drakejacob** [comment]
Oh! Yes, that's true! 
That will probably make it easier then!
