### ISSUE TITLE
Fixa så att horizontal scrollbar inte dyker upp

### ISSUE THREAD

**Issue by drakejacob** [cthit/nollk.it#3]
Sker på "Vi är NollKIT".
Anledningen varför den dyker upp är för att horizontal real estate minskar lite när den vertikala scrollbaren dyker upp.
Den vertikala vill vi ju ha kvar för den är bra, önskar bara att den inte gjorde så att den horisontella dök upp också =(

**Comment by daancs** [comment]
Från vad jag kan se är det för att width är 100viewportwidth vilket gör att den blir en liten horizontelscroll då den vertikala skrollen tar lite plats men räknas inte in i viewportwidth om du fattar va jag menar
