### ISSUE TITLE
host database locally with replication sets

### ISSUE THREAD

**Issue by daancs** [cthit/nollk.it#56]
For now, the database is hosted on the atlasdb cloud since making a local db was difficult. Making replication sets could be made with [this](https://bytelanguage.com/2023/02/13/create-mongo-replicaset-using-docker-compose/). 

The problem currently is that making a replset with mongo version 4.4.18 was hard and I did not have time to figure it out. Upgrading to mongo v.5+ is not currently possible due to the digit-host computer not having a cpu new enough that supports AVX.

**Comment by GAsplund** [comment]
I find this strange as Ivy Bridge CPUs should have AVX support. Maybe it is an issue with the virtualisation layer?
According to [this](https://old.reddit.com/r/homelab/comments/yvo4jm/how_do_i_enable_avx_on_my_server/) thread, the CPU type in Proxmox might have to be changed to "host", which I am unsure of the side effects it might have.

**Comment by Oscariremma** [comment]
According to the [Intel ARC page](https://ark.intel.com/content/www/us/en/ark/products/75789/intel-xeon-processor-e52620-v2-15m-cache-2-10-ghz.html) for the CPU in the current server should support AVX.
![image](https://github.com/cthit/nollk.it/assets/16071372/653f9cc3-9982-4666-a627-79ee2d27169c)
The solution @GAsplund found looks like the correct fix for this and from my research it shouldn't really affect anything as it only adds more instructions by exposing the entire host CPU's features. 
To make the change we will probably need to restart starkiller so there will be a little down time.

**Comment by Oscariremma** [comment]
We have restarted starkiller with all host CPU features enabled so AVX should work now.

**Comment by daancs** [comment]
Have you tried doing anything with this lately? @GAsplund @Oscariremma

**Comment by Oscariremma** [comment]
We have fixed the CPU issue so it should be easy for you to start a local mongodb and move the data to it?

**Comment by daancs** [comment]
Long time since I looked into this but will try to see if I can do it again. Might have to try to fix this on next kod & vin

**Comment by Oscariremma** [comment]
If you want help looking at it then doing it on kod & vin sounds like a good plan.
